// lang.js
var LANG_PACK = {
    'zh-CN': {
        appTitle: '陽光群島巴士路綫查詢系統',
        zhBtn: '中文',
        enBtn: 'English',
        funcTitle: '功能选择',
        routeSelect: '线路站点查询',
        routeSelectDesc: '查询公交线路的站点信息、运营时间',
        updateLog: '更新日志',
        updateLogDesc: '查看版本更新内容和优化记录',
        backBtn: '返回',
        inputTitle: '线路编号输入',
        routeNumberLabel: '线路编号',
        inputPlaceholder: '点击输入线路编号',
        deleteBtn: '删除',
        clearBtn: '清空',
        suggestTitle: '匹配的线路',
        emptySuggest: '请输入线路编号，从建议列表选择',
        noMatchSuggest: '暂无匹配的线路，请检查输入',
        stopPageTitle: '站点信息',
        stopPageTitleWithRoute: '站点信息',
        timetableBtn: '查看运营时间',
        firstBus: '首班车',
        lastBus: '末班车',
        intervalTitle: '发车间隔',
        emptyTimetable: '暂无运营时间数据',
        prevPage: '上一页',
        nextPage: '下一页',
        pageLabel: '第 {current} 页 / 共 {total} 页',
        directionA: '切换至B方向',
        directionB: '切换至A方向',
        loopDirection: '环线方向',
        driveDirection: '行驶方向',
        viaDirection: '途经方向',
        routeType: '线路类型',
        tempClose: '临时关闭',
        stopNumber: '站点序号',
        stopName: '站点名称',
        direction: '目前方向',
        operationTime: '{route} 运营时间',
        outbound: '去程 (A方向)',
        inbound: '回程 (B方向)',
        loop: '环线',
        switchTo: '換爲',
        noInformation: '-',
        normalShift: '常规班次',
        specialShift1: '特殊班次1',
        specialShift2: '特殊班次2',
        specialShift3: '特殊班次3',
        minutesPerTrip: '分钟/班',
        viaLabel: '途經: ',
        tempCloseReason: '关闭原因: ',
        appVersion: '版本',
        loadingTitle: '加载中...',
        initFailed: '应用加载失败，请刷新页面重试！',
        confirm: '确认',
        cancel: '取消',
        circularLine: '(循环线)',
        // 新增更新日志相关翻译
        logVersion: '版本',
        logTime: '更新时间',
        logTitle: '更新日志',
        logEmpty: '暂无更新日志数据',
        logContent: '更新内容',
        // 运营时间面板相关
        switchDirection: '切换方向',
        shiftNormal: '常规班次',
        shiftSpecial: '特殊班次',
        timeSlot: '时段',
        interval: '间隔',
        logAdded: '新增功能',
        logFixed: '问题修复',
        logRemoved: '移除内容',
        logRevamped: '重构优化',
        logImprovements: '其他改进',
        noShiftInformation: '暂无班次信息',
        turningPoint: '转折点',
        shiftName: '班次',
        unknownRoute: '未知路綫'
    },
    'en-US': {
        appTitle: 'Sunshine Islands Bus Route Inquiry System',
        zhBtn: 'Chinese',
        enBtn: 'English',
        funcTitle: 'Function Selection',
        routeSelect: 'Route & Stop Inquiry',
        routeSelectDesc: 'Inquire bus route stops and operation time',
        updateLog: 'Update Log',
        updateLogDesc: 'View version update content and optimization records',
        backBtn: 'Back',
        inputTitle: 'Route Number Input',
        routeNumberLabel: 'Route Number',
        inputPlaceholder: 'Click to enter route number',
        deleteBtn: 'Delete',
        clearBtn: 'Clear',
        suggestTitle: 'Matched Routes',
        emptySuggest: 'Please enter route number and select from suggestions',
        noMatchSuggest: 'No matching routes, please check input',
        stopPageTitle: 'Stop Information',
        stopPageTitleWithRoute: 'Stop Information ',
        timetableBtn: 'View Operation Time',
        firstBus: 'First Bus',
        lastBus: 'Last Bus',
        intervalTitle: 'Departure Interval',
        emptyTimetable: 'No operation time data',
        prevPage: 'Previous Page',
        nextPage: 'Next Page',
        pageLabel: 'Page {current} / Total {total} Pages',
        directionA: 'Switch to B Direction',
        directionB: 'Switch to A Direction',
        loopDirection: 'Loop Direction',
        driveDirection: 'Direction',
        viaDirection: 'Via Direction',
        routeType: 'Route Type',
        tempClose: 'Temporarily Closed',
        stopNumber: 'Stop Number',
        stopName: 'Stop Name',
        direction: 'Current Direction',
        operationTime: '{route} Operation Time',
        outbound: 'Outbound (Direction A)',
        inbound: 'Inbound (Direction B)',
        loop: 'Loop',
        switchTo: 'Switch to',
        noInformation: '-',
        normalShift: 'Regular Service',
        specialShift1: 'Special Service 1',
        specialShift2: 'Special Service 2',
        specialShift3: 'Special Service 3',
        minutesPerTrip: 'mins/trip',
        viaLabel: 'Via: ',
        tempCloseReason: 'Closure Reason: ',
        appVersion: 'Version',
        loadingTitle: 'Loading...',
        initFailed: 'App initialization failed, please refresh and try again!',
        confirm: 'Confirm',
        cancel: 'Cancel',
        circularLine: '(Circular)',
        // 新增更新日志相关翻译
        logVersion: 'Version',
        logTime: 'Update Time',
        logTitle: 'Update Log',
        logEmpty: 'No update log data available',
        logContent: 'Update Content',
        // 运营时间面板相关
        switchDirection: 'Switch Direction',
        shiftNormal: 'Regular Service',
        shiftSpecial: 'Special Service',
        timeSlot: 'Time Slot',
        interval: 'Interval',
        logAdded: 'Added',
        logFixed: 'Fixed',
        logRemoved: 'Removed',
        logRevamped: 'Revamped',
        logImprovements: 'Improvements',
        noShiftInformation: 'No shift information',
        turningPoint: 'Turning Point',
        shiftName: 'Shift Name',
        unknownRoute: 'Unknown route'
    }
};